apiVersion: v1
kind: Service
metadata:
  name: example-plugin
  labels:
    app: example-plugin
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: example-plugin
